# Copyright (c) 2024 rodneyosodo
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
# http://www.apache.org/licenses/LICENSE-2.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "12:00"
      timezone: "Africa/Nairobi"
    assignees:
      - "rodneyosodo"
    groups:
      dev-dependency:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "12:00"
      timezone: "Africa/Nairobi"
    assignees:
      - "rodneyosodo"
    groups:
      dev-dependency:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "./docker"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "12:00"
      timezone: "Africa/Nairobi"
    assignees:
      - "rodneyosodo"
    groups:
      dev-dependency:
        patterns:
          - "*"
