// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	users "github.com/rodneyosodo/twiga/users"
	mock "github.com/stretchr/testify/mock"
)

// FeedRepository is an autogenerated mock type for the FeedRepository type
type FeedRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, feed
func (_m *FeedRepository) Create(ctx context.Context, feed users.Feed) error {
	ret := _m.Called(ctx, feed)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Feed) error); ok {
		r0 = rf(ctx, feed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveAll provides a mock function with given fields: ctx, page
func (_m *FeedRepository) RetrieveAll(ctx context.Context, page users.Page) (users.FeedPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAll")
	}

	var r0 users.FeedPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) (users.FeedPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) users.FeedPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(users.FeedPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFeedRepository creates a new instance of FeedRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeedRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeedRepository {
	mock := &FeedRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
