// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	users "github.com/rodneyosodo/twiga/users"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateFeed provides a mock function with given fields: ctx, feed
func (_m *Service) CreateFeed(ctx context.Context, feed users.Feed) error {
	ret := _m.Called(ctx, feed)

	if len(ret) == 0 {
		panic("no return value specified for CreateFeed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Feed) error); ok {
		r0 = rf(ctx, feed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateFollower provides a mock function with given fields: ctx, following
func (_m *Service) CreateFollower(ctx context.Context, following users.Following) (users.Following, error) {
	ret := _m.Called(ctx, following)

	if len(ret) == 0 {
		panic("no return value specified for CreateFollower")
	}

	var r0 users.Following
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Following) (users.Following, error)); ok {
		return rf(ctx, following)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Following) users.Following); ok {
		r0 = rf(ctx, following)
	} else {
		r0 = ret.Get(0).(users.Following)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Following) error); ok {
		r1 = rf(ctx, following)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePreferences provides a mock function with given fields: ctx, preference
func (_m *Service) CreatePreferences(ctx context.Context, preference users.Preference) (users.Preference, error) {
	ret := _m.Called(ctx, preference)

	if len(ret) == 0 {
		panic("no return value specified for CreatePreferences")
	}

	var r0 users.Preference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Preference) (users.Preference, error)); ok {
		return rf(ctx, preference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Preference) users.Preference); ok {
		r0 = rf(ctx, preference)
	} else {
		r0 = ret.Get(0).(users.Preference)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Preference) error); ok {
		r1 = rf(ctx, preference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *Service) CreateUser(ctx context.Context, user users.User) (users.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.User) (users.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.User) users.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteFollower provides a mock function with given fields: ctx, following
func (_m *Service) DeleteFollower(ctx context.Context, following users.Following) error {
	ret := _m.Called(ctx, following)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFollower")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Following) error); ok {
		r0 = rf(ctx, following)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePreferences provides a mock function with given fields: ctx, userID
func (_m *Service) DeletePreferences(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePreferences")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *Service) DeleteUser(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPreferences provides a mock function with given fields: ctx, page
func (_m *Service) GetPreferences(ctx context.Context, page users.Page) (users.PreferencesPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferences")
	}

	var r0 users.PreferencesPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) (users.PreferencesPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) users.PreferencesPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(users.PreferencesPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreferencesByUserID provides a mock function with given fields: ctx, userID
func (_m *Service) GetPreferencesByUserID(ctx context.Context, userID string) (users.Preference, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferencesByUserID")
	}

	var r0 users.Preference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (users.Preference, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) users.Preference); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(users.Preference)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *Service) GetUserByID(ctx context.Context, id string) (users.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (users.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) users.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserFeed provides a mock function with given fields: ctx, page
func (_m *Service) GetUserFeed(ctx context.Context, page users.Page) (users.FeedPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFeed")
	}

	var r0 users.FeedPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) (users.FeedPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) users.FeedPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(users.FeedPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserFollowings provides a mock function with given fields: ctx, page
func (_m *Service) GetUserFollowings(ctx context.Context, page users.Page) (users.FollowingsPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFollowings")
	}

	var r0 users.FollowingsPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) (users.FollowingsPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) users.FollowingsPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(users.FollowingsPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, page
func (_m *Service) GetUsers(ctx context.Context, page users.Page) (users.UsersPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 users.UsersPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) (users.UsersPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Page) users.UsersPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(users.UsersPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEmailPreferences provides a mock function with given fields: ctx, preference
func (_m *Service) UpdateEmailPreferences(ctx context.Context, preference users.Preference) (users.Preference, error) {
	ret := _m.Called(ctx, preference)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmailPreferences")
	}

	var r0 users.Preference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Preference) (users.Preference, error)); ok {
		return rf(ctx, preference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Preference) users.Preference); ok {
		r0 = rf(ctx, preference)
	} else {
		r0 = ret.Get(0).(users.Preference)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Preference) error); ok {
		r1 = rf(ctx, preference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePreferences provides a mock function with given fields: ctx, preference
func (_m *Service) UpdatePreferences(ctx context.Context, preference users.Preference) (users.Preference, error) {
	ret := _m.Called(ctx, preference)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 users.Preference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Preference) (users.Preference, error)); ok {
		return rf(ctx, preference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Preference) users.Preference); ok {
		r0 = rf(ctx, preference)
	} else {
		r0 = ret.Get(0).(users.Preference)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Preference) error); ok {
		r1 = rf(ctx, preference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePushPreferences provides a mock function with given fields: ctx, preference
func (_m *Service) UpdatePushPreferences(ctx context.Context, preference users.Preference) (users.Preference, error) {
	ret := _m.Called(ctx, preference)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePushPreferences")
	}

	var r0 users.Preference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.Preference) (users.Preference, error)); ok {
		return rf(ctx, preference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.Preference) users.Preference); ok {
		r0 = rf(ctx, preference)
	} else {
		r0 = ret.Get(0).(users.Preference)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.Preference) error); ok {
		r1 = rf(ctx, preference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *Service) UpdateUser(ctx context.Context, user users.User) (users.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.User) (users.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.User) users.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserBio provides a mock function with given fields: ctx, user
func (_m *Service) UpdateUserBio(ctx context.Context, user users.User) (users.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserBio")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.User) (users.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.User) users.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserEmail provides a mock function with given fields: ctx, user
func (_m *Service) UpdateUserEmail(ctx context.Context, user users.User) (users.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserEmail")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.User) (users.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.User) users.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserPassword provides a mock function with given fields: ctx, id, oldPassword, currentPassowrd
func (_m *Service) UpdateUserPassword(ctx context.Context, id string, oldPassword string, currentPassowrd string) (users.User, error) {
	ret := _m.Called(ctx, id, oldPassword, currentPassowrd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (users.User, error)); ok {
		return rf(ctx, id, oldPassword, currentPassowrd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) users.User); ok {
		r0 = rf(ctx, id, oldPassword, currentPassowrd)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, id, oldPassword, currentPassowrd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserPictureURL provides a mock function with given fields: ctx, user
func (_m *Service) UpdateUserPictureURL(ctx context.Context, user users.User) (users.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPictureURL")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.User) (users.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.User) users.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserPreferences provides a mock function with given fields: ctx, user
func (_m *Service) UpdateUserPreferences(ctx context.Context, user users.User) (users.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPreferences")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.User) (users.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.User) users.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserUsername provides a mock function with given fields: ctx, user
func (_m *Service) UpdateUserUsername(ctx context.Context, user users.User) (users.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserUsername")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, users.User) (users.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, users.User) users.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, users.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
