# Copyright (c) 2024 rodneyosodo
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
# http://www.apache.org/licenses/LICENSE-2.0

name: twiga

networks:
  twiga-base-network:
    driver: bridge

volumes:
  twiga-users-db-volume:
  twiga-posts-db-volume:
  twiga-posts-db-config-volume:
  twiga-notifications-db-volume:
  twiga-dragonfly-volume:

services:
  twiga-users-db:
    image: postgres:16.3-alpine
    container_name: twiga-users-db
    restart: on-failure
    networks:
      - twiga-base-network
    volumes:
      - twiga-users-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${TWIGA_USERS_DB_USER}
      POSTGRES_PASSWORD: ${TWIGA_USERS_DB_PASS}
      POSTGRES_DB: ${TWIGA_USERS_DB_NAME}

  twiga-users:
    image: ghcr.io/rodneyosodo/twiga/users:${TWIGA_RELEASE_TAG}
    container_name: twiga-users
    networks:
      - twiga-base-network
    depends_on:
      - twiga-users-db
      - rabbitmq
      - dragonfly
    ports:
      - ${TWIGA_USERS_HTTP_PORT}:${TWIGA_USERS_HTTP_PORT}
      - ${TWIGA_USERS_GRPC_PORT}:${TWIGA_USERS_GRPC_PORT}
    restart: on-failure
    environment:
      TWIGA_USERS_LOG_LEVEL: ${TWIGA_USERS_LOG_LEVEL}
      TWIGA_USERS_JWT_SECRET: ${TWIGA_USERS_JWT_SECRET}
      TWIGA_USERS_JWT_EXP: ${TWIGA_USERS_JWT_EXP}
      TWIGA_JAEGER_URL: ${TWIGA_JAEGER_URL}
      TWIGA_JAEGER_TRACE_RATIO: ${TWIGA_JAEGER_TRACE_RATIO}
      TWIGA_USERS_HTTP_HOST: ${TWIGA_USERS_HTTP_HOST}
      TWIGA_USERS_HTTP_PORT: ${TWIGA_USERS_HTTP_PORT}
      TWIGA_USERS_HTTP_SERVER_CERT: ${TWIGA_USERS_HTTP_SERVER_CERT}
      TWIGA_USERS_HTTP_SERVER_KEY: ${TWIGA_USERS_HTTP_SERVER_KEY}
      TWIGA_USERS_HTTP_SERVER_CA_CERTS: ${TWIGA_USERS_HTTP_SERVER_CA_CERTS}
      TWIGA_USERS_HTTP_CLIENT_CA_CERTS: ${TWIGA_USERS_HTTP_CLIENT_CA_CERTS}
      TWIGA_USERS_GRPC_HOST: ${TWIGA_USERS_GRPC_HOST}
      TWIGA_USERS_GRPC_PORT: ${TWIGA_USERS_GRPC_PORT}
      TWIGA_USERS_GRPC_SERVER_CERT: ${TWIGA_USERS_GRPC_SERVER_CERT}
      TWIGA_USERS_GRPC_SERVER_KEY: ${TWIGA_USERS_GRPC_SERVER_KEY}
      TWIGA_USERS_GRPC_SERVER_CA_CERTS: ${TWIGA_USERS_GRPC_SERVER_CA_CERTS}
      TWIGA_USERS_GRPC_CLIENT_CA_CERTS: ${TWIGA_USERS_GRPC_CLIENT_CA_CERTS}
      TWIGA_USERS_DB_HOST: ${TWIGA_USERS_DB_HOST}
      TWIGA_USERS_DB_PORT: ${TWIGA_USERS_DB_PORT}
      TWIGA_USERS_DB_USER: ${TWIGA_USERS_DB_USER}
      TWIGA_USERS_DB_PASS: ${TWIGA_USERS_DB_PASS}
      TWIGA_USERS_DB_NAME: ${TWIGA_USERS_DB_NAME}
      TWIGA_USERS_DB_SSL_MODE: ${TWIGA_USERS_DB_SSL_MODE}
      TWIGA_USERS_DB_SSL_CERT: ${TWIGA_USERS_DB_SSL_CERT}
      TWIGA_USERS_DB_SSL_KEY: ${TWIGA_USERS_DB_SSL_KEY}
      TWIGA_USERS_DB_SSL_ROOT_CERT: ${TWIGA_USERS_DB_SSL_ROOT_CERT}
      TWIGA_ES_URL: ${TWIGA_ES_URL}
      TWIGA_CACHE_URL: ${TWIGA_CACHE_URL}
      TWIGA_CACHE_KEY_DURATION: ${TWIGA_CACHE_KEY_DURATION}      

  twiga-posts-db:
    image: mongo:7.0.11
    container_name: twiga-posts-db
    restart: on-failure
    networks:
      - twiga-base-network
    environment:
      MONGO_INITDB_DATABASE: ${TWIGA_POSTS_MONGO_DB}
    volumes:
      - twiga-posts-db-volume:/data/db
      - twiga-posts-db-config-volume:/data/configdb

  twiga-posts:
    image: ghcr.io/rodneyosodo/twiga/posts:${TWIGA_RELEASE_TAG}
    container_name: twiga-posts
    networks:
      - twiga-base-network
    depends_on:
      - twiga-posts-db
      - twiga-users
      - rabbitmq
      - dragonfly
    ports:
      - ${TWIGA_POSTS_HTTP_PORT}:${TWIGA_POSTS_HTTP_PORT}
    restart: on-failure
    environment:
      TWIGA_POSTS_LOG_LEVEL: ${TWIGA_POSTS_LOG_LEVEL}
      TWIGA_JAEGER_URL: ${TWIGA_JAEGER_URL}
      TWIGA_JAEGER_TRACE_RATIO: ${TWIGA_JAEGER_TRACE_RATIO}
      TWIGA_POSTS_HTTP_HOST: ${TWIGA_POSTS_HTTP_HOST}
      TWIGA_POSTS_HTTP_PORT: ${TWIGA_POSTS_HTTP_PORT}
      TWIGA_POSTS_HTTP_SERVER_CERT: ${TWIGA_POSTS_HTTP_SERVER_CERT}
      TWIGA_POSTS_HTTP_SERVER_KEY: ${TWIGA_POSTS_HTTP_SERVER_KEY}
      TWIGA_POSTS_HTTP_SERVER_CA_CERTS: ${TWIGA_POSTS_HTTP_SERVER_CA_CERTS}
      TWIGA_POSTS_HTTP_CLIENT_CA_CERTS: ${TWIGA_POSTS_HTTP_CLIENT_CA_CERTS}
      TWIGA_POSTS_MONGO_URL: ${TWIGA_POSTS_MONGO_URL}
      TWIGA_POSTS_MONGO_DB: ${TWIGA_POSTS_MONGO_DB}
      TWIGA_POSTS_MONGO_COLL: ${TWIGA_POSTS_MONGO_COLL}
      TWIGA_USERS_GRPC_URL: ${TWIGA_USERS_GRPC_URL}
      TWIGA_USERS_GRPC_TIMEOUT: ${TWIGA_USERS_GRPC_TIMEOUT}
      TWIGA_USERS_GRPC_CLIENT_CERT: ${TWIGA_USERS_GRPC_CLIENT_CERT}
      TWIGA_USERS_GRPC_CLIENT_KEY: ${TWIGA_USERS_GRPC_CLIENT_KEY}
      TWIGA_USERS_GRPC_SERVER_CA_CERTS: ${TWIGA_USERS_GRPC_SERVER_CA_CERTS}
      TWIGA_ES_URL: ${TWIGA_ES_URL}
      TWIGA_CACHE_URL: ${TWIGA_CACHE_URL}
      TWIGA_CACHE_KEY_DURATION: ${TWIGA_CACHE_KEY_DURATION}      

  twiga-notifications-db:
    image: postgres:16.3-alpine
    container_name: twiga-notifications-db
    restart: on-failure
    networks:
      - twiga-base-network
    volumes:
      - twiga-notifications-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${TWIGA_NOTIFICATIONS_DB_USER}
      POSTGRES_PASSWORD: ${TWIGA_NOTIFICATIONS_DB_PASS}
      POSTGRES_DB: ${TWIGA_NOTIFICATIONS_DB_NAME}

  twiga-notifications:
    image: ghcr.io/rodneyosodo/twiga/notifications:${TWIGA_RELEASE_TAG}
    container_name: twiga-notifications
    networks:
      - twiga-base-network
    depends_on:
      - twiga-notifications-db
      - twiga-users
      - rabbitmq
      - dragonfly
    ports:
      - ${TWIGA_NOTIFICATIONS_HTTP_PORT}:${TWIGA_NOTIFICATIONS_HTTP_PORT}
    restart: on-failure
    environment:
      TWIGA_NOTIFICATIONS_LOG_LEVEL: ${TWIGA_NOTIFICATIONS_LOG_LEVEL}
      TWIGA_JAEGER_URL: ${TWIGA_JAEGER_URL}
      TWIGA_JAEGER_TRACE_RATIO: ${TWIGA_JAEGER_TRACE_RATIO}
      TWIGA_NOTIFICATIONS_HTTP_HOST: ${TWIGA_NOTIFICATIONS_HTTP_HOST}
      TWIGA_NOTIFICATIONS_HTTP_PORT: ${TWIGA_NOTIFICATIONS_HTTP_PORT}
      TWIGA_NOTIFICATIONS_HTTP_SERVER_CERT: ${TWIGA_NOTIFICATIONS_HTTP_SERVER_CERT}
      TWIGA_NOTIFICATIONS_HTTP_SERVER_KEY: ${TWIGA_NOTIFICATIONS_HTTP_SERVER_KEY}
      TWIGA_NOTIFICATIONS_HTTP_SERVER_CA_CERTS: ${TWIGA_NOTIFICATIONS_HTTP_SERVER_CA_CERTS}
      TWIGA_NOTIFICATIONS_HTTP_CLIENT_CA_CERTS: ${TWIGA_NOTIFICATIONS_HTTP_CLIENT_CA_CERTS}
      TWIGA_NOTIFICATIONS_DB_HOST: ${TWIGA_NOTIFICATIONS_DB_HOST}
      TWIGA_NOTIFICATIONS_DB_PORT: ${TWIGA_NOTIFICATIONS_DB_PORT}
      TWIGA_NOTIFICATIONS_DB_USER: ${TWIGA_NOTIFICATIONS_DB_USER}
      TWIGA_NOTIFICATIONS_DB_PASS: ${TWIGA_NOTIFICATIONS_DB_PASS}
      TWIGA_NOTIFICATIONS_DB_NAME: ${TWIGA_NOTIFICATIONS_DB_NAME}
      TWIGA_NOTIFICATIONS_DB_SSL_MODE: ${TWIGA_NOTIFICATIONS_DB_SSL_MODE}
      TWIGA_NOTIFICATIONS_DB_SSL_CERT: ${TWIGA_NOTIFICATIONS_DB_SSL_CERT}
      TWIGA_NOTIFICATIONS_DB_SSL_KEY: ${TWIGA_NOTIFICATIONS_DB_SSL_KEY}
      TWIGA_NOTIFICATIONS_DB_SSL_ROOT_CERT: ${TWIGA_NOTIFICATIONS_DB_SSL_ROOT_CERT}
      TWIGA_USERS_GRPC_URL: ${TWIGA_USERS_GRPC_URL}
      TWIGA_USERS_GRPC_TIMEOUT: ${TWIGA_USERS_GRPC_TIMEOUT}
      TWIGA_USERS_GRPC_CLIENT_CERT: ${TWIGA_USERS_GRPC_CLIENT_CERT}
      TWIGA_USERS_GRPC_CLIENT_KEY: ${TWIGA_USERS_GRPC_CLIENT_KEY}
      TWIGA_USERS_GRPC_SERVER_CA_CERTS: ${TWIGA_USERS_GRPC_SERVER_CA_CERTS}
      TWIGA_ES_URL: ${TWIGA_ES_URL}
      TWIGA_CACHE_URL: ${TWIGA_CACHE_URL}
      TWIGA_CACHE_KEY_DURATION: ${TWIGA_CACHE_KEY_DURATION}

  jaeger:
    image: jaegertracing/all-in-one:1.57.0
    container_name: twiga-jaeger
    restart: on-failure
    networks:
      - twiga-base-network
    ports:
      - ${TWIGA_JAEGER_FRONTEND}:${TWIGA_JAEGER_FRONTEND}
      - ${TWIGA_JAEGER_OLTP_HTTP}:${TWIGA_JAEGER_OLTP_HTTP}
    command: --memory.max-traces ${TWIGA_JAEGER_MEMORY_MAX_TRACES}
    environment:
      COLLECTOR_OTLP_ENABLED: ${TWIGA_JAEGER_COLLECTOR_OTLP_ENABLED}

  rabbitmq:
    image: rabbitmq:3.13.3-management-alpine
    container_name: twiga-rabbitmq
    restart: on-failure
    networks:
      - twiga-base-network
    ports:
      - ${TWIGA_RABBITMQ_PORT}:${TWIGA_RABBITMQ_PORT}
      - ${TWIGA_RABBITMQ_HTTP_PORT}:${TWIGA_RABBITMQ_HTTP_PORT}
    environment:
      RABBITMQ_ERLANG_COOKIE: ${TWIGA_RABBITMQ_COOKIE}
      RABBITMQ_DEFAULT_USER: ${TWIGA_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${TWIGA_RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${TWIGA_RABBITMQ_VHOST}

  dragonfly:
    image: ghcr.io/dragonflydb/dragonfly:v1.19.0
    container_name: twiga-dragonfly
    restart: on-failure
    networks:
      - twiga-base-network
    ports:
      - ${TWIGA_DRAGONFLY_PORT}:${TWIGA_DRAGONFLY_PORT}
    ulimits:
      memlock: -1
    volumes:
      - twiga-dragonfly-volume:/data
