// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	posts "github.com/rodneyosodo/twiga/posts"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, post
func (_m *Repository) Create(ctx context.Context, post posts.Post) (posts.Post, error) {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 posts.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) (posts.Post, error)); ok {
		return rf(ctx, post)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) posts.Post); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Get(0).(posts.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Post) error); ok {
		r1 = rf(ctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateComment provides a mock function with given fields: ctx, postID, comment
func (_m *Repository) CreateComment(ctx context.Context, postID string, comment posts.Comment) (posts.Comment, error) {
	ret := _m.Called(ctx, postID, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 posts.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, posts.Comment) (posts.Comment, error)); ok {
		return rf(ctx, postID, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, posts.Comment) posts.Comment); ok {
		r0 = rf(ctx, postID, comment)
	} else {
		r0 = ret.Get(0).(posts.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, posts.Comment) error); ok {
		r1 = rf(ctx, postID, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLike provides a mock function with given fields: ctx, postID, like
func (_m *Repository) CreateLike(ctx context.Context, postID string, like posts.Like) (posts.Like, error) {
	ret := _m.Called(ctx, postID, like)

	if len(ret) == 0 {
		panic("no return value specified for CreateLike")
	}

	var r0 posts.Like
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, posts.Like) (posts.Like, error)); ok {
		return rf(ctx, postID, like)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, posts.Like) posts.Like); ok {
		r0 = rf(ctx, postID, like)
	} else {
		r0 = ret.Get(0).(posts.Like)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, posts.Like) error); ok {
		r1 = rf(ctx, postID, like)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateShare provides a mock function with given fields: ctx, postID, share
func (_m *Repository) CreateShare(ctx context.Context, postID string, share posts.Share) (posts.Share, error) {
	ret := _m.Called(ctx, postID, share)

	if len(ret) == 0 {
		panic("no return value specified for CreateShare")
	}

	var r0 posts.Share
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, posts.Share) (posts.Share, error)); ok {
		return rf(ctx, postID, share)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, posts.Share) posts.Share); ok {
		r0 = rf(ctx, postID, share)
	} else {
		r0 = ret.Get(0).(posts.Share)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, posts.Share) error); ok {
		r1 = rf(ctx, postID, share)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComment provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteComment(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLike provides a mock function with given fields: ctx, userID
func (_m *Repository) DeleteLike(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteShare provides a mock function with given fields: ctx, userID
func (_m *Repository) DeleteShare(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveAll provides a mock function with given fields: ctx, page
func (_m *Repository) RetrieveAll(ctx context.Context, page posts.Page) (posts.PostsPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAll")
	}

	var r0 posts.PostsPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Page) (posts.PostsPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Page) posts.PostsPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(posts.PostsPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveAllComments provides a mock function with given fields: ctx, page
func (_m *Repository) RetrieveAllComments(ctx context.Context, page posts.Page) (posts.CommentsPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAllComments")
	}

	var r0 posts.CommentsPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Page) (posts.CommentsPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Page) posts.CommentsPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(posts.CommentsPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveAllLikes provides a mock function with given fields: ctx, page
func (_m *Repository) RetrieveAllLikes(ctx context.Context, page posts.Page) (posts.LikesPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAllLikes")
	}

	var r0 posts.LikesPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Page) (posts.LikesPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Page) posts.LikesPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(posts.LikesPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveAllShares provides a mock function with given fields: ctx, page
func (_m *Repository) RetrieveAllShares(ctx context.Context, page posts.Page) (posts.SharesPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAllShares")
	}

	var r0 posts.SharesPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Page) (posts.SharesPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Page) posts.SharesPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(posts.SharesPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveByID provides a mock function with given fields: ctx, id
func (_m *Repository) RetrieveByID(ctx context.Context, id string) (posts.Post, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveByID")
	}

	var r0 posts.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (posts.Post, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) posts.Post); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(posts.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveCommentByID provides a mock function with given fields: ctx, id
func (_m *Repository) RetrieveCommentByID(ctx context.Context, id string) (posts.Comment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveCommentByID")
	}

	var r0 posts.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (posts.Comment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) posts.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(posts.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, post
func (_m *Repository) Update(ctx context.Context, post posts.Post) (posts.Post, error) {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 posts.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) (posts.Post, error)); ok {
		return rf(ctx, post)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) posts.Post); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Get(0).(posts.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Post) error); ok {
		r1 = rf(ctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateComment provides a mock function with given fields: ctx, comment
func (_m *Repository) UpdateComment(ctx context.Context, comment posts.Comment) (posts.Comment, error) {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 posts.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Comment) (posts.Comment, error)); ok {
		return rf(ctx, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Comment) posts.Comment); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Get(0).(posts.Comment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Comment) error); ok {
		r1 = rf(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateContent provides a mock function with given fields: ctx, post
func (_m *Repository) UpdateContent(ctx context.Context, post posts.Post) (posts.Post, error) {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for UpdateContent")
	}

	var r0 posts.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) (posts.Post, error)); ok {
		return rf(ctx, post)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) posts.Post); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Get(0).(posts.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Post) error); ok {
		r1 = rf(ctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateImageURL provides a mock function with given fields: ctx, post
func (_m *Repository) UpdateImageURL(ctx context.Context, post posts.Post) (posts.Post, error) {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImageURL")
	}

	var r0 posts.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) (posts.Post, error)); ok {
		return rf(ctx, post)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) posts.Post); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Get(0).(posts.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Post) error); ok {
		r1 = rf(ctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTags provides a mock function with given fields: ctx, post
func (_m *Repository) UpdateTags(ctx context.Context, post posts.Post) (posts.Post, error) {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTags")
	}

	var r0 posts.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) (posts.Post, error)); ok {
		return rf(ctx, post)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) posts.Post); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Get(0).(posts.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Post) error); ok {
		r1 = rf(ctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVisibility provides a mock function with given fields: ctx, post
func (_m *Repository) UpdateVisibility(ctx context.Context, post posts.Post) (posts.Post, error) {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVisibility")
	}

	var r0 posts.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) (posts.Post, error)); ok {
		return rf(ctx, post)
	}
	if rf, ok := ret.Get(0).(func(context.Context, posts.Post) posts.Post); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Get(0).(posts.Post)
	}

	if rf, ok := ret.Get(1).(func(context.Context, posts.Post) error); ok {
		r1 = rf(ctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
