// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	notifications "github.com/rodneyosodo/twiga/notifications"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateNotification provides a mock function with given fields: ctx, notification
func (_m *Repository) CreateNotification(ctx context.Context, notification notifications.Notification) (notifications.Notification, error) {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, notifications.Notification) (notifications.Notification, error)); ok {
		return rf(ctx, notification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, notifications.Notification) notifications.Notification); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Get(0).(notifications.Notification)
	}

	if rf, ok := ret.Get(1).(func(context.Context, notifications.Notification) error); ok {
		r1 = rf(ctx, notification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNotification provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteNotification(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadAllNotifications provides a mock function with given fields: ctx, page
func (_m *Repository) ReadAllNotifications(ctx context.Context, page notifications.Page) error {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for ReadAllNotifications")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, notifications.Page) error); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadNotification provides a mock function with given fields: ctx, userID, id
func (_m *Repository) ReadNotification(ctx context.Context, userID string, id string) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for ReadNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveAllNotifications provides a mock function with given fields: ctx, page
func (_m *Repository) RetrieveAllNotifications(ctx context.Context, page notifications.Page) (notifications.NotificationsPage, error) {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAllNotifications")
	}

	var r0 notifications.NotificationsPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, notifications.Page) (notifications.NotificationsPage, error)); ok {
		return rf(ctx, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, notifications.Page) notifications.NotificationsPage); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Get(0).(notifications.NotificationsPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, notifications.Page) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveNotification provides a mock function with given fields: ctx, id
func (_m *Repository) RetrieveNotification(ctx context.Context, id string) (notifications.Notification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveNotification")
	}

	var r0 notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (notifications.Notification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) notifications.Notification); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(notifications.Notification)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
