// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	notifications "github.com/rodneyosodo/twiga/notifications"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateNotification provides a mock function with given fields: ctx, token, notification
func (_m *Service) CreateNotification(ctx context.Context, token string, notification notifications.Notification) (notifications.Notification, error) {
	ret := _m.Called(ctx, token, notification)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Notification) (notifications.Notification, error)); ok {
		return rf(ctx, token, notification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Notification) notifications.Notification); ok {
		r0 = rf(ctx, token, notification)
	} else {
		r0 = ret.Get(0).(notifications.Notification)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, notifications.Notification) error); ok {
		r1 = rf(ctx, token, notification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSetting provides a mock function with given fields: ctx, token, setting
func (_m *Service) CreateSetting(ctx context.Context, token string, setting notifications.Setting) (notifications.Setting, error) {
	ret := _m.Called(ctx, token, setting)

	if len(ret) == 0 {
		panic("no return value specified for CreateSetting")
	}

	var r0 notifications.Setting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Setting) (notifications.Setting, error)); ok {
		return rf(ctx, token, setting)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Setting) notifications.Setting); ok {
		r0 = rf(ctx, token, setting)
	} else {
		r0 = ret.Get(0).(notifications.Setting)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, notifications.Setting) error); ok {
		r1 = rf(ctx, token, setting)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNotification provides a mock function with given fields: ctx, token, id
func (_m *Service) DeleteNotification(ctx context.Context, token string, id string) error {
	ret := _m.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSetting provides a mock function with given fields: ctx, token, id
func (_m *Service) DeleteSetting(ctx context.Context, token string, id string) error {
	ret := _m.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSetting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadAllNotifications provides a mock function with given fields: ctx, token, page
func (_m *Service) ReadAllNotifications(ctx context.Context, token string, page notifications.Page) error {
	ret := _m.Called(ctx, token, page)

	if len(ret) == 0 {
		panic("no return value specified for ReadAllNotifications")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Page) error); ok {
		r0 = rf(ctx, token, page)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadNotification provides a mock function with given fields: ctx, token, id
func (_m *Service) ReadNotification(ctx context.Context, token string, id string) error {
	ret := _m.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for ReadNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveAllNotifications provides a mock function with given fields: ctx, token, page
func (_m *Service) RetrieveAllNotifications(ctx context.Context, token string, page notifications.Page) (notifications.NotificationsPage, error) {
	ret := _m.Called(ctx, token, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAllNotifications")
	}

	var r0 notifications.NotificationsPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Page) (notifications.NotificationsPage, error)); ok {
		return rf(ctx, token, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Page) notifications.NotificationsPage); ok {
		r0 = rf(ctx, token, page)
	} else {
		r0 = ret.Get(0).(notifications.NotificationsPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, notifications.Page) error); ok {
		r1 = rf(ctx, token, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveAllSettings provides a mock function with given fields: ctx, token, page
func (_m *Service) RetrieveAllSettings(ctx context.Context, token string, page notifications.Page) (notifications.SettingsPage, error) {
	ret := _m.Called(ctx, token, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAllSettings")
	}

	var r0 notifications.SettingsPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Page) (notifications.SettingsPage, error)); ok {
		return rf(ctx, token, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Page) notifications.SettingsPage); ok {
		r0 = rf(ctx, token, page)
	} else {
		r0 = ret.Get(0).(notifications.SettingsPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, notifications.Page) error); ok {
		r1 = rf(ctx, token, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveNotification provides a mock function with given fields: ctx, token, id
func (_m *Service) RetrieveNotification(ctx context.Context, token string, id string) (notifications.Notification, error) {
	ret := _m.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveNotification")
	}

	var r0 notifications.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (notifications.Notification, error)); ok {
		return rf(ctx, token, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) notifications.Notification); ok {
		r0 = rf(ctx, token, id)
	} else {
		r0 = ret.Get(0).(notifications.Notification)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveSetting provides a mock function with given fields: ctx, token, id
func (_m *Service) RetrieveSetting(ctx context.Context, token string, id string) (notifications.Setting, error) {
	ret := _m.Called(ctx, token, id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveSetting")
	}

	var r0 notifications.Setting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (notifications.Setting, error)); ok {
		return rf(ctx, token, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) notifications.Setting); ok {
		r0 = rf(ctx, token, id)
	} else {
		r0 = ret.Get(0).(notifications.Setting)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEmailSetting provides a mock function with given fields: ctx, token, id, isEnabled
func (_m *Service) UpdateEmailSetting(ctx context.Context, token string, id string, isEnabled bool) error {
	ret := _m.Called(ctx, token, id, isEnabled)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmailSetting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, token, id, isEnabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePushSetting provides a mock function with given fields: ctx, token, id, isEnabled
func (_m *Service) UpdatePushSetting(ctx context.Context, token string, id string, isEnabled bool) error {
	ret := _m.Called(ctx, token, id, isEnabled)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePushSetting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, token, id, isEnabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSetting provides a mock function with given fields: ctx, token, setting
func (_m *Service) UpdateSetting(ctx context.Context, token string, setting notifications.Setting) error {
	ret := _m.Called(ctx, token, setting)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSetting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, notifications.Setting) error); ok {
		r0 = rf(ctx, token, setting)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
